doctrine:
    dbal:
        driver: 'pdo_pgsql'
        host: '%env(DATABASE_HOST)%'
        port: '%env(DATABASE_PORT)%'
        dbname: '%env(DATABASE_NAME)%'
        user: '%env(DATABASE_USER)%'
        password: '%env(DATABASE_PASSWORD)%'
        server_version: 9.6
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Doctrine/Entity'
                prefix: 'App\Doctrine\Entity'
                alias: App

services:
    Doctrine\ORM\EntityManager: '@doctrine.orm.entity_manager'
