doctrine_migrations:
    migrations_paths:
        'App\Doctrine\Migration': '%kernel.project_dir%/src/Doctrine/Migration'
    storage:
        table_storage:
            table_name: migration
            version_column_name: name
            executed_at_column_name: date_executed
    custom_template: '%kernel.project_dir%/code-templates/Doctrine/Migration.php.tpl'
