version: '3.7'

services:

    nginx:
        image: nginx:1.17.7-alpine
        volumes:
            - ./:/var/www
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
            - 443:443
        depends_on:
            - php
        working_dir: /var/www

    php:
        build: .docker/php
        volumes:
            - ./:/var/www
        working_dir: /var/www

    postgres:
        image: postgres:9.6-alpine
        volumes:
            - ./.docker/postgres/data:/var/lib/postgres/data
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE_NAME}

    rabbitmq:
        image: rabbitmq:3.8-management-alpine
        environment:
            RABBITMQ_ERLANG_COOKIE: 'secret'
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
        volumes:
            - ./.docker/rabbitmq/data:/var/lib/rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
